// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: any.proto

package gazebo.msgs;

public final class AnyOuterClass {
  private AnyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gazebo.msgs.Any)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *&#47; &#92;brief Type of value that is contained in this message.
     * </pre>
     *
     * <code>required .gazebo.msgs.Any.ValueType type = 1 [default = NONE];</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     *&#47; &#92;brief Type of value that is contained in this message.
     * </pre>
     *
     * <code>required .gazebo.msgs.Any.ValueType type = 1 [default = NONE];</code>
     * @return The type.
     */
    gazebo.msgs.AnyOuterClass.Any.ValueType getType();

    /**
     * <pre>
     *&#47; &#92;brief A double value
     * </pre>
     *
     * <code>optional double double_value = 2;</code>
     * @return Whether the doubleValue field is set.
     */
    boolean hasDoubleValue();
    /**
     * <pre>
     *&#47; &#92;brief A double value
     * </pre>
     *
     * <code>optional double double_value = 2;</code>
     * @return The doubleValue.
     */
    double getDoubleValue();

    /**
     * <pre>
     *&#47; &#92;brief An int32 value
     * </pre>
     *
     * <code>optional int32 int_value = 3;</code>
     * @return Whether the intValue field is set.
     */
    boolean hasIntValue();
    /**
     * <pre>
     *&#47; &#92;brief An int32 value
     * </pre>
     *
     * <code>optional int32 int_value = 3;</code>
     * @return The intValue.
     */
    int getIntValue();

    /**
     * <pre>
     *&#47; &#92;brief A string value
     * </pre>
     *
     * <code>optional string string_value = 4;</code>
     * @return Whether the stringValue field is set.
     */
    boolean hasStringValue();
    /**
     * <pre>
     *&#47; &#92;brief A string value
     * </pre>
     *
     * <code>optional string string_value = 4;</code>
     * @return The stringValue.
     */
    java.lang.String getStringValue();
    /**
     * <pre>
     *&#47; &#92;brief A string value
     * </pre>
     *
     * <code>optional string string_value = 4;</code>
     * @return The bytes for stringValue.
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <pre>
     *&#47; &#92;brief A boolean value
     * </pre>
     *
     * <code>optional bool bool_value = 5;</code>
     * @return Whether the boolValue field is set.
     */
    boolean hasBoolValue();
    /**
     * <pre>
     *&#47; &#92;brief A boolean value
     * </pre>
     *
     * <code>optional bool bool_value = 5;</code>
     * @return The boolValue.
     */
    boolean getBoolValue();

    /**
     * <pre>
     *&#47; &#92;brief A Vector3d value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
     * @return Whether the vector3dValue field is set.
     */
    boolean hasVector3DValue();
    /**
     * <pre>
     *&#47; &#92;brief A Vector3d value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
     * @return The vector3dValue.
     */
    gazebo.msgs.Vector3D.Vector3d getVector3DValue();
    /**
     * <pre>
     *&#47; &#92;brief A Vector3d value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
     */
    gazebo.msgs.Vector3D.Vector3dOrBuilder getVector3DValueOrBuilder();

    /**
     * <pre>
     *&#47; &#92;brief A Color value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Color color_value = 7;</code>
     * @return Whether the colorValue field is set.
     */
    boolean hasColorValue();
    /**
     * <pre>
     *&#47; &#92;brief A Color value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Color color_value = 7;</code>
     * @return The colorValue.
     */
    gazebo.msgs.ColorOuterClass.Color getColorValue();
    /**
     * <pre>
     *&#47; &#92;brief A Color value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Color color_value = 7;</code>
     */
    gazebo.msgs.ColorOuterClass.ColorOrBuilder getColorValueOrBuilder();

    /**
     * <pre>
     *&#47; &#92;brief A Pose value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
     * @return Whether the pose3dValue field is set.
     */
    boolean hasPose3DValue();
    /**
     * <pre>
     *&#47; &#92;brief A Pose value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
     * @return The pose3dValue.
     */
    gazebo.msgs.PoseOuterClass.Pose getPose3DValue();
    /**
     * <pre>
     *&#47; &#92;brief A Pose value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
     */
    gazebo.msgs.PoseOuterClass.PoseOrBuilder getPose3DValueOrBuilder();

    /**
     * <pre>
     *&#47; &#92;brief A Quaternion value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
     * @return Whether the quaternionValue field is set.
     */
    boolean hasQuaternionValue();
    /**
     * <pre>
     *&#47; &#92;brief A Quaternion value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
     * @return The quaternionValue.
     */
    gazebo.msgs.QuaternionOuterClass.Quaternion getQuaternionValue();
    /**
     * <pre>
     *&#47; &#92;brief A Quaternion value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
     */
    gazebo.msgs.QuaternionOuterClass.QuaternionOrBuilder getQuaternionValueOrBuilder();

    /**
     * <pre>
     *&#47; &#92;brief A Time value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Time time_value = 10;</code>
     * @return Whether the timeValue field is set.
     */
    boolean hasTimeValue();
    /**
     * <pre>
     *&#47; &#92;brief A Time value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Time time_value = 10;</code>
     * @return The timeValue.
     */
    gazebo.msgs.TimeOuterClass.Time getTimeValue();
    /**
     * <pre>
     *&#47; &#92;brief A Time value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Time time_value = 10;</code>
     */
    gazebo.msgs.TimeOuterClass.TimeOrBuilder getTimeValueOrBuilder();
  }
  /**
   * Protobuf type {@code gazebo.msgs.Any}
   */
  public static final class Any extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gazebo.msgs.Any)
      AnyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Any.newBuilder() to construct.
    private Any(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Any() {
      type_ = 1;
      stringValue_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Any();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Any(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              gazebo.msgs.AnyOuterClass.Any.ValueType value = gazebo.msgs.AnyOuterClass.Any.ValueType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              doubleValue_ = input.readDouble();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              intValue_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              stringValue_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              boolValue_ = input.readBool();
              break;
            }
            case 50: {
              gazebo.msgs.Vector3D.Vector3d.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) != 0)) {
                subBuilder = vector3DValue_.toBuilder();
              }
              vector3DValue_ = input.readMessage(gazebo.msgs.Vector3D.Vector3d.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vector3DValue_);
                vector3DValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              gazebo.msgs.ColorOuterClass.Color.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) != 0)) {
                subBuilder = colorValue_.toBuilder();
              }
              colorValue_ = input.readMessage(gazebo.msgs.ColorOuterClass.Color.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(colorValue_);
                colorValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              gazebo.msgs.PoseOuterClass.Pose.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) != 0)) {
                subBuilder = pose3DValue_.toBuilder();
              }
              pose3DValue_ = input.readMessage(gazebo.msgs.PoseOuterClass.Pose.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pose3DValue_);
                pose3DValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
            case 74: {
              gazebo.msgs.QuaternionOuterClass.Quaternion.Builder subBuilder = null;
              if (((bitField0_ & 0x00000100) != 0)) {
                subBuilder = quaternionValue_.toBuilder();
              }
              quaternionValue_ = input.readMessage(gazebo.msgs.QuaternionOuterClass.Quaternion.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(quaternionValue_);
                quaternionValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000100;
              break;
            }
            case 82: {
              gazebo.msgs.TimeOuterClass.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) != 0)) {
                subBuilder = timeValue_.toBuilder();
              }
              timeValue_ = input.readMessage(gazebo.msgs.TimeOuterClass.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timeValue_);
                timeValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gazebo.msgs.AnyOuterClass.internal_static_gazebo_msgs_Any_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gazebo.msgs.AnyOuterClass.internal_static_gazebo_msgs_Any_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gazebo.msgs.AnyOuterClass.Any.class, gazebo.msgs.AnyOuterClass.Any.Builder.class);
    }

    /**
     * <pre>
     *&#47; &#92;brief The type of data the message contains.
     * </pre>
     *
     * Protobuf enum {@code gazebo.msgs.Any.ValueType}
     */
    public enum ValueType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message is empty
       * </pre>
       *
       * <code>NONE = 1;</code>
       */
      NONE(1),
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a double
       * </pre>
       *
       * <code>DOUBLE = 2;</code>
       */
      DOUBLE(2),
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains an int32
       * </pre>
       *
       * <code>INT32 = 3;</code>
       */
      INT32(3),
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a string
       * </pre>
       *
       * <code>STRING = 4;</code>
       */
      STRING(4),
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Boolean
       * </pre>
       *
       * <code>BOOLEAN = 5;</code>
       */
      BOOLEAN(5),
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Vector3d
       * </pre>
       *
       * <code>VECTOR3D = 6;</code>
       */
      VECTOR3D(6),
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Color
       * </pre>
       *
       * <code>COLOR = 7;</code>
       */
      COLOR(7),
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Pose
       * </pre>
       *
       * <code>POSE3D = 8;</code>
       */
      POSE3D(8),
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Quaternion
       * </pre>
       *
       * <code>QUATERNIOND = 9;</code>
       */
      QUATERNIOND(9),
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Time
       * </pre>
       *
       * <code>TIME = 10;</code>
       */
      TIME(10),
      ;

      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message is empty
       * </pre>
       *
       * <code>NONE = 1;</code>
       */
      public static final int NONE_VALUE = 1;
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a double
       * </pre>
       *
       * <code>DOUBLE = 2;</code>
       */
      public static final int DOUBLE_VALUE = 2;
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains an int32
       * </pre>
       *
       * <code>INT32 = 3;</code>
       */
      public static final int INT32_VALUE = 3;
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a string
       * </pre>
       *
       * <code>STRING = 4;</code>
       */
      public static final int STRING_VALUE = 4;
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Boolean
       * </pre>
       *
       * <code>BOOLEAN = 5;</code>
       */
      public static final int BOOLEAN_VALUE = 5;
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Vector3d
       * </pre>
       *
       * <code>VECTOR3D = 6;</code>
       */
      public static final int VECTOR3D_VALUE = 6;
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Color
       * </pre>
       *
       * <code>COLOR = 7;</code>
       */
      public static final int COLOR_VALUE = 7;
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Pose
       * </pre>
       *
       * <code>POSE3D = 8;</code>
       */
      public static final int POSE3D_VALUE = 8;
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Quaternion
       * </pre>
       *
       * <code>QUATERNIOND = 9;</code>
       */
      public static final int QUATERNIOND_VALUE = 9;
      /**
       * <pre>
       *&#47; &#92;brief Indicates that the message contains a Time
       * </pre>
       *
       * <code>TIME = 10;</code>
       */
      public static final int TIME_VALUE = 10;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ValueType forNumber(int value) {
        switch (value) {
          case 1: return NONE;
          case 2: return DOUBLE;
          case 3: return INT32;
          case 4: return STRING;
          case 5: return BOOLEAN;
          case 6: return VECTOR3D;
          case 7: return COLOR;
          case 8: return POSE3D;
          case 9: return QUATERNIOND;
          case 10: return TIME;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ValueType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
              public ValueType findValueByNumber(int number) {
                return ValueType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gazebo.msgs.AnyOuterClass.Any.getDescriptor().getEnumTypes().get(0);
      }

      private static final ValueType[] VALUES = values();

      public static ValueType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ValueType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:gazebo.msgs.Any.ValueType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *&#47; &#92;brief Type of value that is contained in this message.
     * </pre>
     *
     * <code>required .gazebo.msgs.Any.ValueType type = 1 [default = NONE];</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief Type of value that is contained in this message.
     * </pre>
     *
     * <code>required .gazebo.msgs.Any.ValueType type = 1 [default = NONE];</code>
     * @return The type.
     */
    @java.lang.Override public gazebo.msgs.AnyOuterClass.Any.ValueType getType() {
      @SuppressWarnings("deprecation")
      gazebo.msgs.AnyOuterClass.Any.ValueType result = gazebo.msgs.AnyOuterClass.Any.ValueType.valueOf(type_);
      return result == null ? gazebo.msgs.AnyOuterClass.Any.ValueType.NONE : result;
    }

    public static final int DOUBLE_VALUE_FIELD_NUMBER = 2;
    private double doubleValue_;
    /**
     * <pre>
     *&#47; &#92;brief A double value
     * </pre>
     *
     * <code>optional double double_value = 2;</code>
     * @return Whether the doubleValue field is set.
     */
    @java.lang.Override
    public boolean hasDoubleValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief A double value
     * </pre>
     *
     * <code>optional double double_value = 2;</code>
     * @return The doubleValue.
     */
    @java.lang.Override
    public double getDoubleValue() {
      return doubleValue_;
    }

    public static final int INT_VALUE_FIELD_NUMBER = 3;
    private int intValue_;
    /**
     * <pre>
     *&#47; &#92;brief An int32 value
     * </pre>
     *
     * <code>optional int32 int_value = 3;</code>
     * @return Whether the intValue field is set.
     */
    @java.lang.Override
    public boolean hasIntValue() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief An int32 value
     * </pre>
     *
     * <code>optional int32 int_value = 3;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public int getIntValue() {
      return intValue_;
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object stringValue_;
    /**
     * <pre>
     *&#47; &#92;brief A string value
     * </pre>
     *
     * <code>optional string string_value = 4;</code>
     * @return Whether the stringValue field is set.
     */
    @java.lang.Override
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief A string value
     * </pre>
     *
     * <code>optional string string_value = 4;</code>
     * @return The stringValue.
     */
    @java.lang.Override
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringValue_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *&#47; &#92;brief A string value
     * </pre>
     *
     * <code>optional string string_value = 4;</code>
     * @return The bytes for stringValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOL_VALUE_FIELD_NUMBER = 5;
    private boolean boolValue_;
    /**
     * <pre>
     *&#47; &#92;brief A boolean value
     * </pre>
     *
     * <code>optional bool bool_value = 5;</code>
     * @return Whether the boolValue field is set.
     */
    @java.lang.Override
    public boolean hasBoolValue() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief A boolean value
     * </pre>
     *
     * <code>optional bool bool_value = 5;</code>
     * @return The boolValue.
     */
    @java.lang.Override
    public boolean getBoolValue() {
      return boolValue_;
    }

    public static final int VECTOR3D_VALUE_FIELD_NUMBER = 6;
    private gazebo.msgs.Vector3D.Vector3d vector3DValue_;
    /**
     * <pre>
     *&#47; &#92;brief A Vector3d value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
     * @return Whether the vector3dValue field is set.
     */
    @java.lang.Override
    public boolean hasVector3DValue() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief A Vector3d value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
     * @return The vector3dValue.
     */
    @java.lang.Override
    public gazebo.msgs.Vector3D.Vector3d getVector3DValue() {
      return vector3DValue_ == null ? gazebo.msgs.Vector3D.Vector3d.getDefaultInstance() : vector3DValue_;
    }
    /**
     * <pre>
     *&#47; &#92;brief A Vector3d value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
     */
    @java.lang.Override
    public gazebo.msgs.Vector3D.Vector3dOrBuilder getVector3DValueOrBuilder() {
      return vector3DValue_ == null ? gazebo.msgs.Vector3D.Vector3d.getDefaultInstance() : vector3DValue_;
    }

    public static final int COLOR_VALUE_FIELD_NUMBER = 7;
    private gazebo.msgs.ColorOuterClass.Color colorValue_;
    /**
     * <pre>
     *&#47; &#92;brief A Color value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Color color_value = 7;</code>
     * @return Whether the colorValue field is set.
     */
    @java.lang.Override
    public boolean hasColorValue() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief A Color value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Color color_value = 7;</code>
     * @return The colorValue.
     */
    @java.lang.Override
    public gazebo.msgs.ColorOuterClass.Color getColorValue() {
      return colorValue_ == null ? gazebo.msgs.ColorOuterClass.Color.getDefaultInstance() : colorValue_;
    }
    /**
     * <pre>
     *&#47; &#92;brief A Color value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Color color_value = 7;</code>
     */
    @java.lang.Override
    public gazebo.msgs.ColorOuterClass.ColorOrBuilder getColorValueOrBuilder() {
      return colorValue_ == null ? gazebo.msgs.ColorOuterClass.Color.getDefaultInstance() : colorValue_;
    }

    public static final int POSE3D_VALUE_FIELD_NUMBER = 8;
    private gazebo.msgs.PoseOuterClass.Pose pose3DValue_;
    /**
     * <pre>
     *&#47; &#92;brief A Pose value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
     * @return Whether the pose3dValue field is set.
     */
    @java.lang.Override
    public boolean hasPose3DValue() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief A Pose value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
     * @return The pose3dValue.
     */
    @java.lang.Override
    public gazebo.msgs.PoseOuterClass.Pose getPose3DValue() {
      return pose3DValue_ == null ? gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance() : pose3DValue_;
    }
    /**
     * <pre>
     *&#47; &#92;brief A Pose value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
     */
    @java.lang.Override
    public gazebo.msgs.PoseOuterClass.PoseOrBuilder getPose3DValueOrBuilder() {
      return pose3DValue_ == null ? gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance() : pose3DValue_;
    }

    public static final int QUATERNION_VALUE_FIELD_NUMBER = 9;
    private gazebo.msgs.QuaternionOuterClass.Quaternion quaternionValue_;
    /**
     * <pre>
     *&#47; &#92;brief A Quaternion value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
     * @return Whether the quaternionValue field is set.
     */
    @java.lang.Override
    public boolean hasQuaternionValue() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief A Quaternion value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
     * @return The quaternionValue.
     */
    @java.lang.Override
    public gazebo.msgs.QuaternionOuterClass.Quaternion getQuaternionValue() {
      return quaternionValue_ == null ? gazebo.msgs.QuaternionOuterClass.Quaternion.getDefaultInstance() : quaternionValue_;
    }
    /**
     * <pre>
     *&#47; &#92;brief A Quaternion value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
     */
    @java.lang.Override
    public gazebo.msgs.QuaternionOuterClass.QuaternionOrBuilder getQuaternionValueOrBuilder() {
      return quaternionValue_ == null ? gazebo.msgs.QuaternionOuterClass.Quaternion.getDefaultInstance() : quaternionValue_;
    }

    public static final int TIME_VALUE_FIELD_NUMBER = 10;
    private gazebo.msgs.TimeOuterClass.Time timeValue_;
    /**
     * <pre>
     *&#47; &#92;brief A Time value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Time time_value = 10;</code>
     * @return Whether the timeValue field is set.
     */
    @java.lang.Override
    public boolean hasTimeValue() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     *&#47; &#92;brief A Time value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Time time_value = 10;</code>
     * @return The timeValue.
     */
    @java.lang.Override
    public gazebo.msgs.TimeOuterClass.Time getTimeValue() {
      return timeValue_ == null ? gazebo.msgs.TimeOuterClass.Time.getDefaultInstance() : timeValue_;
    }
    /**
     * <pre>
     *&#47; &#92;brief A Time value
     * </pre>
     *
     * <code>optional .gazebo.msgs.Time time_value = 10;</code>
     */
    @java.lang.Override
    public gazebo.msgs.TimeOuterClass.TimeOrBuilder getTimeValueOrBuilder() {
      return timeValue_ == null ? gazebo.msgs.TimeOuterClass.Time.getDefaultInstance() : timeValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasVector3DValue()) {
        if (!getVector3DValue().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasColorValue()) {
        if (!getColorValue().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasPose3DValue()) {
        if (!getPose3DValue().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasQuaternionValue()) {
        if (!getQuaternionValue().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTimeValue()) {
        if (!getTimeValue().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, doubleValue_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, intValue_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, stringValue_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, boolValue_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeMessage(6, getVector3DValue());
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeMessage(7, getColorValue());
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeMessage(8, getPose3DValue());
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeMessage(9, getQuaternionValue());
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeMessage(10, getTimeValue());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, doubleValue_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, intValue_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, stringValue_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, boolValue_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getVector3DValue());
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getColorValue());
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getPose3DValue());
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getQuaternionValue());
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getTimeValue());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gazebo.msgs.AnyOuterClass.Any)) {
        return super.equals(obj);
      }
      gazebo.msgs.AnyOuterClass.Any other = (gazebo.msgs.AnyOuterClass.Any) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasDoubleValue() != other.hasDoubleValue()) return false;
      if (hasDoubleValue()) {
        if (java.lang.Double.doubleToLongBits(getDoubleValue())
            != java.lang.Double.doubleToLongBits(
                other.getDoubleValue())) return false;
      }
      if (hasIntValue() != other.hasIntValue()) return false;
      if (hasIntValue()) {
        if (getIntValue()
            != other.getIntValue()) return false;
      }
      if (hasStringValue() != other.hasStringValue()) return false;
      if (hasStringValue()) {
        if (!getStringValue()
            .equals(other.getStringValue())) return false;
      }
      if (hasBoolValue() != other.hasBoolValue()) return false;
      if (hasBoolValue()) {
        if (getBoolValue()
            != other.getBoolValue()) return false;
      }
      if (hasVector3DValue() != other.hasVector3DValue()) return false;
      if (hasVector3DValue()) {
        if (!getVector3DValue()
            .equals(other.getVector3DValue())) return false;
      }
      if (hasColorValue() != other.hasColorValue()) return false;
      if (hasColorValue()) {
        if (!getColorValue()
            .equals(other.getColorValue())) return false;
      }
      if (hasPose3DValue() != other.hasPose3DValue()) return false;
      if (hasPose3DValue()) {
        if (!getPose3DValue()
            .equals(other.getPose3DValue())) return false;
      }
      if (hasQuaternionValue() != other.hasQuaternionValue()) return false;
      if (hasQuaternionValue()) {
        if (!getQuaternionValue()
            .equals(other.getQuaternionValue())) return false;
      }
      if (hasTimeValue() != other.hasTimeValue()) return false;
      if (hasTimeValue()) {
        if (!getTimeValue()
            .equals(other.getTimeValue())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasDoubleValue()) {
        hash = (37 * hash) + DOUBLE_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDoubleValue()));
      }
      if (hasIntValue()) {
        hash = (37 * hash) + INT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getIntValue();
      }
      if (hasStringValue()) {
        hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValue().hashCode();
      }
      if (hasBoolValue()) {
        hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolValue());
      }
      if (hasVector3DValue()) {
        hash = (37 * hash) + VECTOR3D_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getVector3DValue().hashCode();
      }
      if (hasColorValue()) {
        hash = (37 * hash) + COLOR_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getColorValue().hashCode();
      }
      if (hasPose3DValue()) {
        hash = (37 * hash) + POSE3D_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getPose3DValue().hashCode();
      }
      if (hasQuaternionValue()) {
        hash = (37 * hash) + QUATERNION_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getQuaternionValue().hashCode();
      }
      if (hasTimeValue()) {
        hash = (37 * hash) + TIME_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getTimeValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gazebo.msgs.AnyOuterClass.Any parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gazebo.msgs.AnyOuterClass.Any parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gazebo.msgs.AnyOuterClass.Any prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.Any}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gazebo.msgs.Any)
        gazebo.msgs.AnyOuterClass.AnyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gazebo.msgs.AnyOuterClass.internal_static_gazebo_msgs_Any_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gazebo.msgs.AnyOuterClass.internal_static_gazebo_msgs_Any_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gazebo.msgs.AnyOuterClass.Any.class, gazebo.msgs.AnyOuterClass.Any.Builder.class);
      }

      // Construct using gazebo.msgs.AnyOuterClass.Any.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVector3DValueFieldBuilder();
          getColorValueFieldBuilder();
          getPose3DValueFieldBuilder();
          getQuaternionValueFieldBuilder();
          getTimeValueFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        doubleValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        intValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        stringValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        boolValue_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (vector3DValueBuilder_ == null) {
          vector3DValue_ = null;
        } else {
          vector3DValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (colorValueBuilder_ == null) {
          colorValue_ = null;
        } else {
          colorValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (pose3DValueBuilder_ == null) {
          pose3DValue_ = null;
        } else {
          pose3DValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        if (quaternionValueBuilder_ == null) {
          quaternionValue_ = null;
        } else {
          quaternionValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        if (timeValueBuilder_ == null) {
          timeValue_ = null;
        } else {
          timeValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gazebo.msgs.AnyOuterClass.internal_static_gazebo_msgs_Any_descriptor;
      }

      @java.lang.Override
      public gazebo.msgs.AnyOuterClass.Any getDefaultInstanceForType() {
        return gazebo.msgs.AnyOuterClass.Any.getDefaultInstance();
      }

      @java.lang.Override
      public gazebo.msgs.AnyOuterClass.Any build() {
        gazebo.msgs.AnyOuterClass.Any result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public gazebo.msgs.AnyOuterClass.Any buildPartial() {
        gazebo.msgs.AnyOuterClass.Any result = new gazebo.msgs.AnyOuterClass.Any(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.doubleValue_ = doubleValue_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.intValue_ = intValue_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.stringValue_ = stringValue_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.boolValue_ = boolValue_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          if (vector3DValueBuilder_ == null) {
            result.vector3DValue_ = vector3DValue_;
          } else {
            result.vector3DValue_ = vector3DValueBuilder_.build();
          }
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          if (colorValueBuilder_ == null) {
            result.colorValue_ = colorValue_;
          } else {
            result.colorValue_ = colorValueBuilder_.build();
          }
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          if (pose3DValueBuilder_ == null) {
            result.pose3DValue_ = pose3DValue_;
          } else {
            result.pose3DValue_ = pose3DValueBuilder_.build();
          }
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          if (quaternionValueBuilder_ == null) {
            result.quaternionValue_ = quaternionValue_;
          } else {
            result.quaternionValue_ = quaternionValueBuilder_.build();
          }
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          if (timeValueBuilder_ == null) {
            result.timeValue_ = timeValue_;
          } else {
            result.timeValue_ = timeValueBuilder_.build();
          }
          to_bitField0_ |= 0x00000200;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gazebo.msgs.AnyOuterClass.Any) {
          return mergeFrom((gazebo.msgs.AnyOuterClass.Any)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gazebo.msgs.AnyOuterClass.Any other) {
        if (other == gazebo.msgs.AnyOuterClass.Any.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDoubleValue()) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.hasIntValue()) {
          setIntValue(other.getIntValue());
        }
        if (other.hasStringValue()) {
          bitField0_ |= 0x00000008;
          stringValue_ = other.stringValue_;
          onChanged();
        }
        if (other.hasBoolValue()) {
          setBoolValue(other.getBoolValue());
        }
        if (other.hasVector3DValue()) {
          mergeVector3DValue(other.getVector3DValue());
        }
        if (other.hasColorValue()) {
          mergeColorValue(other.getColorValue());
        }
        if (other.hasPose3DValue()) {
          mergePose3DValue(other.getPose3DValue());
        }
        if (other.hasQuaternionValue()) {
          mergeQuaternionValue(other.getQuaternionValue());
        }
        if (other.hasTimeValue()) {
          mergeTimeValue(other.getTimeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (hasVector3DValue()) {
          if (!getVector3DValue().isInitialized()) {
            return false;
          }
        }
        if (hasColorValue()) {
          if (!getColorValue().isInitialized()) {
            return false;
          }
        }
        if (hasPose3DValue()) {
          if (!getPose3DValue().isInitialized()) {
            return false;
          }
        }
        if (hasQuaternionValue()) {
          if (!getQuaternionValue().isInitialized()) {
            return false;
          }
        }
        if (hasTimeValue()) {
          if (!getTimeValue().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gazebo.msgs.AnyOuterClass.Any parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gazebo.msgs.AnyOuterClass.Any) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 1;
      /**
       * <pre>
       *&#47; &#92;brief Type of value that is contained in this message.
       * </pre>
       *
       * <code>required .gazebo.msgs.Any.ValueType type = 1 [default = NONE];</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief Type of value that is contained in this message.
       * </pre>
       *
       * <code>required .gazebo.msgs.Any.ValueType type = 1 [default = NONE];</code>
       * @return The type.
       */
      @java.lang.Override
      public gazebo.msgs.AnyOuterClass.Any.ValueType getType() {
        @SuppressWarnings("deprecation")
        gazebo.msgs.AnyOuterClass.Any.ValueType result = gazebo.msgs.AnyOuterClass.Any.ValueType.valueOf(type_);
        return result == null ? gazebo.msgs.AnyOuterClass.Any.ValueType.NONE : result;
      }
      /**
       * <pre>
       *&#47; &#92;brief Type of value that is contained in this message.
       * </pre>
       *
       * <code>required .gazebo.msgs.Any.ValueType type = 1 [default = NONE];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(gazebo.msgs.AnyOuterClass.Any.ValueType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief Type of value that is contained in this message.
       * </pre>
       *
       * <code>required .gazebo.msgs.Any.ValueType type = 1 [default = NONE];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private double doubleValue_ ;
      /**
       * <pre>
       *&#47; &#92;brief A double value
       * </pre>
       *
       * <code>optional double double_value = 2;</code>
       * @return Whether the doubleValue field is set.
       */
      @java.lang.Override
      public boolean hasDoubleValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief A double value
       * </pre>
       *
       * <code>optional double double_value = 2;</code>
       * @return The doubleValue.
       */
      @java.lang.Override
      public double getDoubleValue() {
        return doubleValue_;
      }
      /**
       * <pre>
       *&#47; &#92;brief A double value
       * </pre>
       *
       * <code>optional double double_value = 2;</code>
       * @param value The doubleValue to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleValue(double value) {
        bitField0_ |= 0x00000002;
        doubleValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A double value
       * </pre>
       *
       * <code>optional double double_value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        doubleValue_ = 0D;
        onChanged();
        return this;
      }

      private int intValue_ ;
      /**
       * <pre>
       *&#47; &#92;brief An int32 value
       * </pre>
       *
       * <code>optional int32 int_value = 3;</code>
       * @return Whether the intValue field is set.
       */
      @java.lang.Override
      public boolean hasIntValue() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief An int32 value
       * </pre>
       *
       * <code>optional int32 int_value = 3;</code>
       * @return The intValue.
       */
      @java.lang.Override
      public int getIntValue() {
        return intValue_;
      }
      /**
       * <pre>
       *&#47; &#92;brief An int32 value
       * </pre>
       *
       * <code>optional int32 int_value = 3;</code>
       * @param value The intValue to set.
       * @return This builder for chaining.
       */
      public Builder setIntValue(int value) {
        bitField0_ |= 0x00000004;
        intValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief An int32 value
       * </pre>
       *
       * <code>optional int32 int_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        intValue_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object stringValue_ = "";
      /**
       * <pre>
       *&#47; &#92;brief A string value
       * </pre>
       *
       * <code>optional string string_value = 4;</code>
       * @return Whether the stringValue field is set.
       */
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief A string value
       * </pre>
       *
       * <code>optional string string_value = 4;</code>
       * @return The stringValue.
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stringValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A string value
       * </pre>
       *
       * <code>optional string string_value = 4;</code>
       * @return The bytes for stringValue.
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A string value
       * </pre>
       *
       * <code>optional string string_value = 4;</code>
       * @param value The stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        stringValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A string value
       * </pre>
       *
       * <code>optional string string_value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A string value
       * </pre>
       *
       * <code>optional string string_value = 4;</code>
       * @param value The bytes for stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        stringValue_ = value;
        onChanged();
        return this;
      }

      private boolean boolValue_ ;
      /**
       * <pre>
       *&#47; &#92;brief A boolean value
       * </pre>
       *
       * <code>optional bool bool_value = 5;</code>
       * @return Whether the boolValue field is set.
       */
      @java.lang.Override
      public boolean hasBoolValue() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief A boolean value
       * </pre>
       *
       * <code>optional bool bool_value = 5;</code>
       * @return The boolValue.
       */
      @java.lang.Override
      public boolean getBoolValue() {
        return boolValue_;
      }
      /**
       * <pre>
       *&#47; &#92;brief A boolean value
       * </pre>
       *
       * <code>optional bool bool_value = 5;</code>
       * @param value The boolValue to set.
       * @return This builder for chaining.
       */
      public Builder setBoolValue(boolean value) {
        bitField0_ |= 0x00000010;
        boolValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A boolean value
       * </pre>
       *
       * <code>optional bool bool_value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        boolValue_ = false;
        onChanged();
        return this;
      }

      private gazebo.msgs.Vector3D.Vector3d vector3DValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.Vector3D.Vector3d, gazebo.msgs.Vector3D.Vector3d.Builder, gazebo.msgs.Vector3D.Vector3dOrBuilder> vector3DValueBuilder_;
      /**
       * <pre>
       *&#47; &#92;brief A Vector3d value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
       * @return Whether the vector3dValue field is set.
       */
      public boolean hasVector3DValue() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief A Vector3d value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
       * @return The vector3dValue.
       */
      public gazebo.msgs.Vector3D.Vector3d getVector3DValue() {
        if (vector3DValueBuilder_ == null) {
          return vector3DValue_ == null ? gazebo.msgs.Vector3D.Vector3d.getDefaultInstance() : vector3DValue_;
        } else {
          return vector3DValueBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Vector3d value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
       */
      public Builder setVector3DValue(gazebo.msgs.Vector3D.Vector3d value) {
        if (vector3DValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vector3DValue_ = value;
          onChanged();
        } else {
          vector3DValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Vector3d value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
       */
      public Builder setVector3DValue(
          gazebo.msgs.Vector3D.Vector3d.Builder builderForValue) {
        if (vector3DValueBuilder_ == null) {
          vector3DValue_ = builderForValue.build();
          onChanged();
        } else {
          vector3DValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Vector3d value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
       */
      public Builder mergeVector3DValue(gazebo.msgs.Vector3D.Vector3d value) {
        if (vector3DValueBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
              vector3DValue_ != null &&
              vector3DValue_ != gazebo.msgs.Vector3D.Vector3d.getDefaultInstance()) {
            vector3DValue_ =
              gazebo.msgs.Vector3D.Vector3d.newBuilder(vector3DValue_).mergeFrom(value).buildPartial();
          } else {
            vector3DValue_ = value;
          }
          onChanged();
        } else {
          vector3DValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Vector3d value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
       */
      public Builder clearVector3DValue() {
        if (vector3DValueBuilder_ == null) {
          vector3DValue_ = null;
          onChanged();
        } else {
          vector3DValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Vector3d value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
       */
      public gazebo.msgs.Vector3D.Vector3d.Builder getVector3DValueBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getVector3DValueFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *&#47; &#92;brief A Vector3d value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
       */
      public gazebo.msgs.Vector3D.Vector3dOrBuilder getVector3DValueOrBuilder() {
        if (vector3DValueBuilder_ != null) {
          return vector3DValueBuilder_.getMessageOrBuilder();
        } else {
          return vector3DValue_ == null ?
              gazebo.msgs.Vector3D.Vector3d.getDefaultInstance() : vector3DValue_;
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Vector3d value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Vector3d vector3d_value = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.Vector3D.Vector3d, gazebo.msgs.Vector3D.Vector3d.Builder, gazebo.msgs.Vector3D.Vector3dOrBuilder> 
          getVector3DValueFieldBuilder() {
        if (vector3DValueBuilder_ == null) {
          vector3DValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gazebo.msgs.Vector3D.Vector3d, gazebo.msgs.Vector3D.Vector3d.Builder, gazebo.msgs.Vector3D.Vector3dOrBuilder>(
                  getVector3DValue(),
                  getParentForChildren(),
                  isClean());
          vector3DValue_ = null;
        }
        return vector3DValueBuilder_;
      }

      private gazebo.msgs.ColorOuterClass.Color colorValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.ColorOuterClass.Color, gazebo.msgs.ColorOuterClass.Color.Builder, gazebo.msgs.ColorOuterClass.ColorOrBuilder> colorValueBuilder_;
      /**
       * <pre>
       *&#47; &#92;brief A Color value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Color color_value = 7;</code>
       * @return Whether the colorValue field is set.
       */
      public boolean hasColorValue() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief A Color value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Color color_value = 7;</code>
       * @return The colorValue.
       */
      public gazebo.msgs.ColorOuterClass.Color getColorValue() {
        if (colorValueBuilder_ == null) {
          return colorValue_ == null ? gazebo.msgs.ColorOuterClass.Color.getDefaultInstance() : colorValue_;
        } else {
          return colorValueBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Color value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Color color_value = 7;</code>
       */
      public Builder setColorValue(gazebo.msgs.ColorOuterClass.Color value) {
        if (colorValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          colorValue_ = value;
          onChanged();
        } else {
          colorValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Color value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Color color_value = 7;</code>
       */
      public Builder setColorValue(
          gazebo.msgs.ColorOuterClass.Color.Builder builderForValue) {
        if (colorValueBuilder_ == null) {
          colorValue_ = builderForValue.build();
          onChanged();
        } else {
          colorValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Color value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Color color_value = 7;</code>
       */
      public Builder mergeColorValue(gazebo.msgs.ColorOuterClass.Color value) {
        if (colorValueBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
              colorValue_ != null &&
              colorValue_ != gazebo.msgs.ColorOuterClass.Color.getDefaultInstance()) {
            colorValue_ =
              gazebo.msgs.ColorOuterClass.Color.newBuilder(colorValue_).mergeFrom(value).buildPartial();
          } else {
            colorValue_ = value;
          }
          onChanged();
        } else {
          colorValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Color value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Color color_value = 7;</code>
       */
      public Builder clearColorValue() {
        if (colorValueBuilder_ == null) {
          colorValue_ = null;
          onChanged();
        } else {
          colorValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Color value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Color color_value = 7;</code>
       */
      public gazebo.msgs.ColorOuterClass.Color.Builder getColorValueBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getColorValueFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *&#47; &#92;brief A Color value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Color color_value = 7;</code>
       */
      public gazebo.msgs.ColorOuterClass.ColorOrBuilder getColorValueOrBuilder() {
        if (colorValueBuilder_ != null) {
          return colorValueBuilder_.getMessageOrBuilder();
        } else {
          return colorValue_ == null ?
              gazebo.msgs.ColorOuterClass.Color.getDefaultInstance() : colorValue_;
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Color value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Color color_value = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.ColorOuterClass.Color, gazebo.msgs.ColorOuterClass.Color.Builder, gazebo.msgs.ColorOuterClass.ColorOrBuilder> 
          getColorValueFieldBuilder() {
        if (colorValueBuilder_ == null) {
          colorValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gazebo.msgs.ColorOuterClass.Color, gazebo.msgs.ColorOuterClass.Color.Builder, gazebo.msgs.ColorOuterClass.ColorOrBuilder>(
                  getColorValue(),
                  getParentForChildren(),
                  isClean());
          colorValue_ = null;
        }
        return colorValueBuilder_;
      }

      private gazebo.msgs.PoseOuterClass.Pose pose3DValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.PoseOuterClass.Pose, gazebo.msgs.PoseOuterClass.Pose.Builder, gazebo.msgs.PoseOuterClass.PoseOrBuilder> pose3DValueBuilder_;
      /**
       * <pre>
       *&#47; &#92;brief A Pose value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
       * @return Whether the pose3dValue field is set.
       */
      public boolean hasPose3DValue() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief A Pose value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
       * @return The pose3dValue.
       */
      public gazebo.msgs.PoseOuterClass.Pose getPose3DValue() {
        if (pose3DValueBuilder_ == null) {
          return pose3DValue_ == null ? gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance() : pose3DValue_;
        } else {
          return pose3DValueBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Pose value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
       */
      public Builder setPose3DValue(gazebo.msgs.PoseOuterClass.Pose value) {
        if (pose3DValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pose3DValue_ = value;
          onChanged();
        } else {
          pose3DValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Pose value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
       */
      public Builder setPose3DValue(
          gazebo.msgs.PoseOuterClass.Pose.Builder builderForValue) {
        if (pose3DValueBuilder_ == null) {
          pose3DValue_ = builderForValue.build();
          onChanged();
        } else {
          pose3DValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Pose value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
       */
      public Builder mergePose3DValue(gazebo.msgs.PoseOuterClass.Pose value) {
        if (pose3DValueBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0) &&
              pose3DValue_ != null &&
              pose3DValue_ != gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance()) {
            pose3DValue_ =
              gazebo.msgs.PoseOuterClass.Pose.newBuilder(pose3DValue_).mergeFrom(value).buildPartial();
          } else {
            pose3DValue_ = value;
          }
          onChanged();
        } else {
          pose3DValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Pose value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
       */
      public Builder clearPose3DValue() {
        if (pose3DValueBuilder_ == null) {
          pose3DValue_ = null;
          onChanged();
        } else {
          pose3DValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Pose value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
       */
      public gazebo.msgs.PoseOuterClass.Pose.Builder getPose3DValueBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getPose3DValueFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *&#47; &#92;brief A Pose value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
       */
      public gazebo.msgs.PoseOuterClass.PoseOrBuilder getPose3DValueOrBuilder() {
        if (pose3DValueBuilder_ != null) {
          return pose3DValueBuilder_.getMessageOrBuilder();
        } else {
          return pose3DValue_ == null ?
              gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance() : pose3DValue_;
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Pose value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Pose pose3d_value = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.PoseOuterClass.Pose, gazebo.msgs.PoseOuterClass.Pose.Builder, gazebo.msgs.PoseOuterClass.PoseOrBuilder> 
          getPose3DValueFieldBuilder() {
        if (pose3DValueBuilder_ == null) {
          pose3DValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gazebo.msgs.PoseOuterClass.Pose, gazebo.msgs.PoseOuterClass.Pose.Builder, gazebo.msgs.PoseOuterClass.PoseOrBuilder>(
                  getPose3DValue(),
                  getParentForChildren(),
                  isClean());
          pose3DValue_ = null;
        }
        return pose3DValueBuilder_;
      }

      private gazebo.msgs.QuaternionOuterClass.Quaternion quaternionValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.QuaternionOuterClass.Quaternion, gazebo.msgs.QuaternionOuterClass.Quaternion.Builder, gazebo.msgs.QuaternionOuterClass.QuaternionOrBuilder> quaternionValueBuilder_;
      /**
       * <pre>
       *&#47; &#92;brief A Quaternion value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
       * @return Whether the quaternionValue field is set.
       */
      public boolean hasQuaternionValue() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief A Quaternion value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
       * @return The quaternionValue.
       */
      public gazebo.msgs.QuaternionOuterClass.Quaternion getQuaternionValue() {
        if (quaternionValueBuilder_ == null) {
          return quaternionValue_ == null ? gazebo.msgs.QuaternionOuterClass.Quaternion.getDefaultInstance() : quaternionValue_;
        } else {
          return quaternionValueBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Quaternion value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
       */
      public Builder setQuaternionValue(gazebo.msgs.QuaternionOuterClass.Quaternion value) {
        if (quaternionValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          quaternionValue_ = value;
          onChanged();
        } else {
          quaternionValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Quaternion value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
       */
      public Builder setQuaternionValue(
          gazebo.msgs.QuaternionOuterClass.Quaternion.Builder builderForValue) {
        if (quaternionValueBuilder_ == null) {
          quaternionValue_ = builderForValue.build();
          onChanged();
        } else {
          quaternionValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Quaternion value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
       */
      public Builder mergeQuaternionValue(gazebo.msgs.QuaternionOuterClass.Quaternion value) {
        if (quaternionValueBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0) &&
              quaternionValue_ != null &&
              quaternionValue_ != gazebo.msgs.QuaternionOuterClass.Quaternion.getDefaultInstance()) {
            quaternionValue_ =
              gazebo.msgs.QuaternionOuterClass.Quaternion.newBuilder(quaternionValue_).mergeFrom(value).buildPartial();
          } else {
            quaternionValue_ = value;
          }
          onChanged();
        } else {
          quaternionValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Quaternion value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
       */
      public Builder clearQuaternionValue() {
        if (quaternionValueBuilder_ == null) {
          quaternionValue_ = null;
          onChanged();
        } else {
          quaternionValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Quaternion value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
       */
      public gazebo.msgs.QuaternionOuterClass.Quaternion.Builder getQuaternionValueBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getQuaternionValueFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *&#47; &#92;brief A Quaternion value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
       */
      public gazebo.msgs.QuaternionOuterClass.QuaternionOrBuilder getQuaternionValueOrBuilder() {
        if (quaternionValueBuilder_ != null) {
          return quaternionValueBuilder_.getMessageOrBuilder();
        } else {
          return quaternionValue_ == null ?
              gazebo.msgs.QuaternionOuterClass.Quaternion.getDefaultInstance() : quaternionValue_;
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Quaternion value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Quaternion quaternion_value = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.QuaternionOuterClass.Quaternion, gazebo.msgs.QuaternionOuterClass.Quaternion.Builder, gazebo.msgs.QuaternionOuterClass.QuaternionOrBuilder> 
          getQuaternionValueFieldBuilder() {
        if (quaternionValueBuilder_ == null) {
          quaternionValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gazebo.msgs.QuaternionOuterClass.Quaternion, gazebo.msgs.QuaternionOuterClass.Quaternion.Builder, gazebo.msgs.QuaternionOuterClass.QuaternionOrBuilder>(
                  getQuaternionValue(),
                  getParentForChildren(),
                  isClean());
          quaternionValue_ = null;
        }
        return quaternionValueBuilder_;
      }

      private gazebo.msgs.TimeOuterClass.Time timeValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.TimeOuterClass.Time, gazebo.msgs.TimeOuterClass.Time.Builder, gazebo.msgs.TimeOuterClass.TimeOrBuilder> timeValueBuilder_;
      /**
       * <pre>
       *&#47; &#92;brief A Time value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Time time_value = 10;</code>
       * @return Whether the timeValue field is set.
       */
      public boolean hasTimeValue() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <pre>
       *&#47; &#92;brief A Time value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Time time_value = 10;</code>
       * @return The timeValue.
       */
      public gazebo.msgs.TimeOuterClass.Time getTimeValue() {
        if (timeValueBuilder_ == null) {
          return timeValue_ == null ? gazebo.msgs.TimeOuterClass.Time.getDefaultInstance() : timeValue_;
        } else {
          return timeValueBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Time value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Time time_value = 10;</code>
       */
      public Builder setTimeValue(gazebo.msgs.TimeOuterClass.Time value) {
        if (timeValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timeValue_ = value;
          onChanged();
        } else {
          timeValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Time value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Time time_value = 10;</code>
       */
      public Builder setTimeValue(
          gazebo.msgs.TimeOuterClass.Time.Builder builderForValue) {
        if (timeValueBuilder_ == null) {
          timeValue_ = builderForValue.build();
          onChanged();
        } else {
          timeValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Time value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Time time_value = 10;</code>
       */
      public Builder mergeTimeValue(gazebo.msgs.TimeOuterClass.Time value) {
        if (timeValueBuilder_ == null) {
          if (((bitField0_ & 0x00000200) != 0) &&
              timeValue_ != null &&
              timeValue_ != gazebo.msgs.TimeOuterClass.Time.getDefaultInstance()) {
            timeValue_ =
              gazebo.msgs.TimeOuterClass.Time.newBuilder(timeValue_).mergeFrom(value).buildPartial();
          } else {
            timeValue_ = value;
          }
          onChanged();
        } else {
          timeValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Time value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Time time_value = 10;</code>
       */
      public Builder clearTimeValue() {
        if (timeValueBuilder_ == null) {
          timeValue_ = null;
          onChanged();
        } else {
          timeValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      /**
       * <pre>
       *&#47; &#92;brief A Time value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Time time_value = 10;</code>
       */
      public gazebo.msgs.TimeOuterClass.Time.Builder getTimeValueBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getTimeValueFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *&#47; &#92;brief A Time value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Time time_value = 10;</code>
       */
      public gazebo.msgs.TimeOuterClass.TimeOrBuilder getTimeValueOrBuilder() {
        if (timeValueBuilder_ != null) {
          return timeValueBuilder_.getMessageOrBuilder();
        } else {
          return timeValue_ == null ?
              gazebo.msgs.TimeOuterClass.Time.getDefaultInstance() : timeValue_;
        }
      }
      /**
       * <pre>
       *&#47; &#92;brief A Time value
       * </pre>
       *
       * <code>optional .gazebo.msgs.Time time_value = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.TimeOuterClass.Time, gazebo.msgs.TimeOuterClass.Time.Builder, gazebo.msgs.TimeOuterClass.TimeOrBuilder> 
          getTimeValueFieldBuilder() {
        if (timeValueBuilder_ == null) {
          timeValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gazebo.msgs.TimeOuterClass.Time, gazebo.msgs.TimeOuterClass.Time.Builder, gazebo.msgs.TimeOuterClass.TimeOrBuilder>(
                  getTimeValue(),
                  getParentForChildren(),
                  isClean());
          timeValue_ = null;
        }
        return timeValueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gazebo.msgs.Any)
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.Any)
    private static final gazebo.msgs.AnyOuterClass.Any DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gazebo.msgs.AnyOuterClass.Any();
    }

    public static gazebo.msgs.AnyOuterClass.Any getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Any>
        PARSER = new com.google.protobuf.AbstractParser<Any>() {
      @java.lang.Override
      public Any parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Any(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Any> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Any> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public gazebo.msgs.AnyOuterClass.Any getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_Any_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gazebo_msgs_Any_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tany.proto\022\013gazebo.msgs\032\013color.proto\032\np" +
      "ose.proto\032\020quaternion.proto\032\ntime.proto\032" +
      "\016vector3d.proto\"\353\003\n\003Any\022.\n\004type\030\001 \002(\0162\032." +
      "gazebo.msgs.Any.ValueType:\004NONE\022\024\n\014doubl" +
      "e_value\030\002 \001(\001\022\021\n\tint_value\030\003 \001(\005\022\024\n\014stri" +
      "ng_value\030\004 \001(\t\022\022\n\nbool_value\030\005 \001(\010\022-\n\016ve" +
      "ctor3d_value\030\006 \001(\0132\025.gazebo.msgs.Vector3" +
      "d\022\'\n\013color_value\030\007 \001(\0132\022.gazebo.msgs.Col" +
      "or\022\'\n\014pose3d_value\030\010 \001(\0132\021.gazebo.msgs.P" +
      "ose\0221\n\020quaternion_value\030\t \001(\0132\027.gazebo.m" +
      "sgs.Quaternion\022%\n\ntime_value\030\n \001(\0132\021.gaz" +
      "ebo.msgs.Time\"\205\001\n\tValueType\022\010\n\004NONE\020\001\022\n\n" +
      "\006DOUBLE\020\002\022\t\n\005INT32\020\003\022\n\n\006STRING\020\004\022\013\n\007BOOL" +
      "EAN\020\005\022\014\n\010VECTOR3D\020\006\022\t\n\005COLOR\020\007\022\n\n\006POSE3D" +
      "\020\010\022\017\n\013QUATERNIOND\020\t\022\010\n\004TIME\020\n"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gazebo.msgs.ColorOuterClass.getDescriptor(),
          gazebo.msgs.PoseOuterClass.getDescriptor(),
          gazebo.msgs.QuaternionOuterClass.getDescriptor(),
          gazebo.msgs.TimeOuterClass.getDescriptor(),
          gazebo.msgs.Vector3D.getDescriptor(),
        });
    internal_static_gazebo_msgs_Any_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gazebo_msgs_Any_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gazebo_msgs_Any_descriptor,
        new java.lang.String[] { "Type", "DoubleValue", "IntValue", "StringValue", "BoolValue", "Vector3DValue", "ColorValue", "Pose3DValue", "QuaternionValue", "TimeValue", });
    gazebo.msgs.ColorOuterClass.getDescriptor();
    gazebo.msgs.PoseOuterClass.getDescriptor();
    gazebo.msgs.QuaternionOuterClass.getDescriptor();
    gazebo.msgs.TimeOuterClass.getDescriptor();
    gazebo.msgs.Vector3D.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
