// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gui.proto

package gazebo.msgs;

public final class Gui {
  private Gui() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GUIOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gazebo.msgs.GUI)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool fullscreen = 1;</code>
     * @return Whether the fullscreen field is set.
     */
    boolean hasFullscreen();
    /**
     * <code>optional bool fullscreen = 1;</code>
     * @return The fullscreen.
     */
    boolean getFullscreen();

    /**
     * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
     * @return Whether the camera field is set.
     */
    boolean hasCamera();
    /**
     * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
     * @return The camera.
     */
    gazebo.msgs.GuiCamera.GUICamera getCamera();
    /**
     * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
     */
    gazebo.msgs.GuiCamera.GUICameraOrBuilder getCameraOrBuilder();

    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    java.util.List<gazebo.msgs.PluginOuterClass.Plugin> 
        getPluginList();
    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    gazebo.msgs.PluginOuterClass.Plugin getPlugin(int index);
    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    int getPluginCount();
    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    java.util.List<? extends gazebo.msgs.PluginOuterClass.PluginOrBuilder> 
        getPluginOrBuilderList();
    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    gazebo.msgs.PluginOuterClass.PluginOrBuilder getPluginOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gazebo.msgs.GUI}
   */
  public static final class GUI extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gazebo.msgs.GUI)
      GUIOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GUI.newBuilder() to construct.
    private GUI(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GUI() {
      plugin_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GUI();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gazebo.msgs.Gui.internal_static_gazebo_msgs_GUI_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gazebo.msgs.Gui.internal_static_gazebo_msgs_GUI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gazebo.msgs.Gui.GUI.class, gazebo.msgs.Gui.GUI.Builder.class);
    }

    private int bitField0_;
    public static final int FULLSCREEN_FIELD_NUMBER = 1;
    private boolean fullscreen_ = false;
    /**
     * <code>optional bool fullscreen = 1;</code>
     * @return Whether the fullscreen field is set.
     */
    @java.lang.Override
    public boolean hasFullscreen() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool fullscreen = 1;</code>
     * @return The fullscreen.
     */
    @java.lang.Override
    public boolean getFullscreen() {
      return fullscreen_;
    }

    public static final int CAMERA_FIELD_NUMBER = 2;
    private gazebo.msgs.GuiCamera.GUICamera camera_;
    /**
     * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
     * @return Whether the camera field is set.
     */
    @java.lang.Override
    public boolean hasCamera() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
     * @return The camera.
     */
    @java.lang.Override
    public gazebo.msgs.GuiCamera.GUICamera getCamera() {
      return camera_ == null ? gazebo.msgs.GuiCamera.GUICamera.getDefaultInstance() : camera_;
    }
    /**
     * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
     */
    @java.lang.Override
    public gazebo.msgs.GuiCamera.GUICameraOrBuilder getCameraOrBuilder() {
      return camera_ == null ? gazebo.msgs.GuiCamera.GUICamera.getDefaultInstance() : camera_;
    }

    public static final int PLUGIN_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<gazebo.msgs.PluginOuterClass.Plugin> plugin_;
    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    @java.lang.Override
    public java.util.List<gazebo.msgs.PluginOuterClass.Plugin> getPluginList() {
      return plugin_;
    }
    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends gazebo.msgs.PluginOuterClass.PluginOrBuilder> 
        getPluginOrBuilderList() {
      return plugin_;
    }
    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    @java.lang.Override
    public int getPluginCount() {
      return plugin_.size();
    }
    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    @java.lang.Override
    public gazebo.msgs.PluginOuterClass.Plugin getPlugin(int index) {
      return plugin_.get(index);
    }
    /**
     * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
     */
    @java.lang.Override
    public gazebo.msgs.PluginOuterClass.PluginOrBuilder getPluginOrBuilder(
        int index) {
      return plugin_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasCamera()) {
        if (!getCamera().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getPluginCount(); i++) {
        if (!getPlugin(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, fullscreen_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getCamera());
      }
      for (int i = 0; i < plugin_.size(); i++) {
        output.writeMessage(3, plugin_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, fullscreen_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCamera());
      }
      for (int i = 0; i < plugin_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, plugin_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gazebo.msgs.Gui.GUI)) {
        return super.equals(obj);
      }
      gazebo.msgs.Gui.GUI other = (gazebo.msgs.Gui.GUI) obj;

      if (hasFullscreen() != other.hasFullscreen()) return false;
      if (hasFullscreen()) {
        if (getFullscreen()
            != other.getFullscreen()) return false;
      }
      if (hasCamera() != other.hasCamera()) return false;
      if (hasCamera()) {
        if (!getCamera()
            .equals(other.getCamera())) return false;
      }
      if (!getPluginList()
          .equals(other.getPluginList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFullscreen()) {
        hash = (37 * hash) + FULLSCREEN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getFullscreen());
      }
      if (hasCamera()) {
        hash = (37 * hash) + CAMERA_FIELD_NUMBER;
        hash = (53 * hash) + getCamera().hashCode();
      }
      if (getPluginCount() > 0) {
        hash = (37 * hash) + PLUGIN_FIELD_NUMBER;
        hash = (53 * hash) + getPluginList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gazebo.msgs.Gui.GUI parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.Gui.GUI parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.Gui.GUI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.Gui.GUI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.Gui.GUI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.Gui.GUI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.Gui.GUI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gazebo.msgs.Gui.GUI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gazebo.msgs.Gui.GUI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gazebo.msgs.Gui.GUI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gazebo.msgs.Gui.GUI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gazebo.msgs.Gui.GUI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gazebo.msgs.Gui.GUI prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.GUI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gazebo.msgs.GUI)
        gazebo.msgs.Gui.GUIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gazebo.msgs.Gui.internal_static_gazebo_msgs_GUI_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gazebo.msgs.Gui.internal_static_gazebo_msgs_GUI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gazebo.msgs.Gui.GUI.class, gazebo.msgs.Gui.GUI.Builder.class);
      }

      // Construct using gazebo.msgs.Gui.GUI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCameraFieldBuilder();
          getPluginFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fullscreen_ = false;
        camera_ = null;
        if (cameraBuilder_ != null) {
          cameraBuilder_.dispose();
          cameraBuilder_ = null;
        }
        if (pluginBuilder_ == null) {
          plugin_ = java.util.Collections.emptyList();
        } else {
          plugin_ = null;
          pluginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gazebo.msgs.Gui.internal_static_gazebo_msgs_GUI_descriptor;
      }

      @java.lang.Override
      public gazebo.msgs.Gui.GUI getDefaultInstanceForType() {
        return gazebo.msgs.Gui.GUI.getDefaultInstance();
      }

      @java.lang.Override
      public gazebo.msgs.Gui.GUI build() {
        gazebo.msgs.Gui.GUI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public gazebo.msgs.Gui.GUI buildPartial() {
        gazebo.msgs.Gui.GUI result = new gazebo.msgs.Gui.GUI(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(gazebo.msgs.Gui.GUI result) {
        if (pluginBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            plugin_ = java.util.Collections.unmodifiableList(plugin_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.plugin_ = plugin_;
        } else {
          result.plugin_ = pluginBuilder_.build();
        }
      }

      private void buildPartial0(gazebo.msgs.Gui.GUI result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fullscreen_ = fullscreen_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.camera_ = cameraBuilder_ == null
              ? camera_
              : cameraBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gazebo.msgs.Gui.GUI) {
          return mergeFrom((gazebo.msgs.Gui.GUI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gazebo.msgs.Gui.GUI other) {
        if (other == gazebo.msgs.Gui.GUI.getDefaultInstance()) return this;
        if (other.hasFullscreen()) {
          setFullscreen(other.getFullscreen());
        }
        if (other.hasCamera()) {
          mergeCamera(other.getCamera());
        }
        if (pluginBuilder_ == null) {
          if (!other.plugin_.isEmpty()) {
            if (plugin_.isEmpty()) {
              plugin_ = other.plugin_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePluginIsMutable();
              plugin_.addAll(other.plugin_);
            }
            onChanged();
          }
        } else {
          if (!other.plugin_.isEmpty()) {
            if (pluginBuilder_.isEmpty()) {
              pluginBuilder_.dispose();
              pluginBuilder_ = null;
              plugin_ = other.plugin_;
              bitField0_ = (bitField0_ & ~0x00000004);
              pluginBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPluginFieldBuilder() : null;
            } else {
              pluginBuilder_.addAllMessages(other.plugin_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasCamera()) {
          if (!getCamera().isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getPluginCount(); i++) {
          if (!getPlugin(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                fullscreen_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getCameraFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                gazebo.msgs.PluginOuterClass.Plugin m =
                    input.readMessage(
                        gazebo.msgs.PluginOuterClass.Plugin.PARSER,
                        extensionRegistry);
                if (pluginBuilder_ == null) {
                  ensurePluginIsMutable();
                  plugin_.add(m);
                } else {
                  pluginBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean fullscreen_ ;
      /**
       * <code>optional bool fullscreen = 1;</code>
       * @return Whether the fullscreen field is set.
       */
      @java.lang.Override
      public boolean hasFullscreen() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool fullscreen = 1;</code>
       * @return The fullscreen.
       */
      @java.lang.Override
      public boolean getFullscreen() {
        return fullscreen_;
      }
      /**
       * <code>optional bool fullscreen = 1;</code>
       * @param value The fullscreen to set.
       * @return This builder for chaining.
       */
      public Builder setFullscreen(boolean value) {
        
        fullscreen_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool fullscreen = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFullscreen() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fullscreen_ = false;
        onChanged();
        return this;
      }

      private gazebo.msgs.GuiCamera.GUICamera camera_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.GuiCamera.GUICamera, gazebo.msgs.GuiCamera.GUICamera.Builder, gazebo.msgs.GuiCamera.GUICameraOrBuilder> cameraBuilder_;
      /**
       * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
       * @return Whether the camera field is set.
       */
      public boolean hasCamera() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
       * @return The camera.
       */
      public gazebo.msgs.GuiCamera.GUICamera getCamera() {
        if (cameraBuilder_ == null) {
          return camera_ == null ? gazebo.msgs.GuiCamera.GUICamera.getDefaultInstance() : camera_;
        } else {
          return cameraBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
       */
      public Builder setCamera(gazebo.msgs.GuiCamera.GUICamera value) {
        if (cameraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          camera_ = value;
        } else {
          cameraBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
       */
      public Builder setCamera(
          gazebo.msgs.GuiCamera.GUICamera.Builder builderForValue) {
        if (cameraBuilder_ == null) {
          camera_ = builderForValue.build();
        } else {
          cameraBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
       */
      public Builder mergeCamera(gazebo.msgs.GuiCamera.GUICamera value) {
        if (cameraBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            camera_ != null &&
            camera_ != gazebo.msgs.GuiCamera.GUICamera.getDefaultInstance()) {
            getCameraBuilder().mergeFrom(value);
          } else {
            camera_ = value;
          }
        } else {
          cameraBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
       */
      public Builder clearCamera() {
        bitField0_ = (bitField0_ & ~0x00000002);
        camera_ = null;
        if (cameraBuilder_ != null) {
          cameraBuilder_.dispose();
          cameraBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
       */
      public gazebo.msgs.GuiCamera.GUICamera.Builder getCameraBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCameraFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
       */
      public gazebo.msgs.GuiCamera.GUICameraOrBuilder getCameraOrBuilder() {
        if (cameraBuilder_ != null) {
          return cameraBuilder_.getMessageOrBuilder();
        } else {
          return camera_ == null ?
              gazebo.msgs.GuiCamera.GUICamera.getDefaultInstance() : camera_;
        }
      }
      /**
       * <code>optional .gazebo.msgs.GUICamera camera = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.GuiCamera.GUICamera, gazebo.msgs.GuiCamera.GUICamera.Builder, gazebo.msgs.GuiCamera.GUICameraOrBuilder> 
          getCameraFieldBuilder() {
        if (cameraBuilder_ == null) {
          cameraBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gazebo.msgs.GuiCamera.GUICamera, gazebo.msgs.GuiCamera.GUICamera.Builder, gazebo.msgs.GuiCamera.GUICameraOrBuilder>(
                  getCamera(),
                  getParentForChildren(),
                  isClean());
          camera_ = null;
        }
        return cameraBuilder_;
      }

      private java.util.List<gazebo.msgs.PluginOuterClass.Plugin> plugin_ =
        java.util.Collections.emptyList();
      private void ensurePluginIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          plugin_ = new java.util.ArrayList<gazebo.msgs.PluginOuterClass.Plugin>(plugin_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          gazebo.msgs.PluginOuterClass.Plugin, gazebo.msgs.PluginOuterClass.Plugin.Builder, gazebo.msgs.PluginOuterClass.PluginOrBuilder> pluginBuilder_;

      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public java.util.List<gazebo.msgs.PluginOuterClass.Plugin> getPluginList() {
        if (pluginBuilder_ == null) {
          return java.util.Collections.unmodifiableList(plugin_);
        } else {
          return pluginBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public int getPluginCount() {
        if (pluginBuilder_ == null) {
          return plugin_.size();
        } else {
          return pluginBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public gazebo.msgs.PluginOuterClass.Plugin getPlugin(int index) {
        if (pluginBuilder_ == null) {
          return plugin_.get(index);
        } else {
          return pluginBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public Builder setPlugin(
          int index, gazebo.msgs.PluginOuterClass.Plugin value) {
        if (pluginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePluginIsMutable();
          plugin_.set(index, value);
          onChanged();
        } else {
          pluginBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public Builder setPlugin(
          int index, gazebo.msgs.PluginOuterClass.Plugin.Builder builderForValue) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          plugin_.set(index, builderForValue.build());
          onChanged();
        } else {
          pluginBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public Builder addPlugin(gazebo.msgs.PluginOuterClass.Plugin value) {
        if (pluginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePluginIsMutable();
          plugin_.add(value);
          onChanged();
        } else {
          pluginBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public Builder addPlugin(
          int index, gazebo.msgs.PluginOuterClass.Plugin value) {
        if (pluginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePluginIsMutable();
          plugin_.add(index, value);
          onChanged();
        } else {
          pluginBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public Builder addPlugin(
          gazebo.msgs.PluginOuterClass.Plugin.Builder builderForValue) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          plugin_.add(builderForValue.build());
          onChanged();
        } else {
          pluginBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public Builder addPlugin(
          int index, gazebo.msgs.PluginOuterClass.Plugin.Builder builderForValue) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          plugin_.add(index, builderForValue.build());
          onChanged();
        } else {
          pluginBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public Builder addAllPlugin(
          java.lang.Iterable<? extends gazebo.msgs.PluginOuterClass.Plugin> values) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, plugin_);
          onChanged();
        } else {
          pluginBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public Builder clearPlugin() {
        if (pluginBuilder_ == null) {
          plugin_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          pluginBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public Builder removePlugin(int index) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          plugin_.remove(index);
          onChanged();
        } else {
          pluginBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public gazebo.msgs.PluginOuterClass.Plugin.Builder getPluginBuilder(
          int index) {
        return getPluginFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public gazebo.msgs.PluginOuterClass.PluginOrBuilder getPluginOrBuilder(
          int index) {
        if (pluginBuilder_ == null) {
          return plugin_.get(index);  } else {
          return pluginBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public java.util.List<? extends gazebo.msgs.PluginOuterClass.PluginOrBuilder> 
           getPluginOrBuilderList() {
        if (pluginBuilder_ != null) {
          return pluginBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(plugin_);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public gazebo.msgs.PluginOuterClass.Plugin.Builder addPluginBuilder() {
        return getPluginFieldBuilder().addBuilder(
            gazebo.msgs.PluginOuterClass.Plugin.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public gazebo.msgs.PluginOuterClass.Plugin.Builder addPluginBuilder(
          int index) {
        return getPluginFieldBuilder().addBuilder(
            index, gazebo.msgs.PluginOuterClass.Plugin.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Plugin plugin = 3;</code>
       */
      public java.util.List<gazebo.msgs.PluginOuterClass.Plugin.Builder> 
           getPluginBuilderList() {
        return getPluginFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          gazebo.msgs.PluginOuterClass.Plugin, gazebo.msgs.PluginOuterClass.Plugin.Builder, gazebo.msgs.PluginOuterClass.PluginOrBuilder> 
          getPluginFieldBuilder() {
        if (pluginBuilder_ == null) {
          pluginBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              gazebo.msgs.PluginOuterClass.Plugin, gazebo.msgs.PluginOuterClass.Plugin.Builder, gazebo.msgs.PluginOuterClass.PluginOrBuilder>(
                  plugin_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          plugin_ = null;
        }
        return pluginBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gazebo.msgs.GUI)
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.GUI)
    private static final gazebo.msgs.Gui.GUI DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gazebo.msgs.Gui.GUI();
    }

    public static gazebo.msgs.Gui.GUI getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GUI>
        PARSER = new com.google.protobuf.AbstractParser<GUI>() {
      @java.lang.Override
      public GUI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GUI> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GUI> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public gazebo.msgs.Gui.GUI getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_GUI_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gazebo_msgs_GUI_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tgui.proto\022\013gazebo.msgs\032\020gui_camera.pro" +
      "to\032\014plugin.proto\"f\n\003GUI\022\022\n\nfullscreen\030\001 " +
      "\001(\010\022&\n\006camera\030\002 \001(\0132\026.gazebo.msgs.GUICam" +
      "era\022#\n\006plugin\030\003 \003(\0132\023.gazebo.msgs.Plugin"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gazebo.msgs.GuiCamera.getDescriptor(),
          gazebo.msgs.PluginOuterClass.getDescriptor(),
        });
    internal_static_gazebo_msgs_GUI_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gazebo_msgs_GUI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gazebo_msgs_GUI_descriptor,
        new java.lang.String[] { "Fullscreen", "Camera", "Plugin", });
    gazebo.msgs.GuiCamera.getDescriptor();
    gazebo.msgs.PluginOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
