// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose_stamped.proto

package gazebo.msgs;

public final class PoseStampedOuterClass {
  private PoseStampedOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PoseStampedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gazebo.msgs.PoseStamped)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Time when the data was captured
     * </pre>
     *
     * <code>required .gazebo.msgs.Time time = 1;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <pre>
     * Time when the data was captured
     * </pre>
     *
     * <code>required .gazebo.msgs.Time time = 1;</code>
     * @return The time.
     */
    gazebo.msgs.TimeOuterClass.Time getTime();
    /**
     * <pre>
     * Time when the data was captured
     * </pre>
     *
     * <code>required .gazebo.msgs.Time time = 1;</code>
     */
    gazebo.msgs.TimeOuterClass.TimeOrBuilder getTimeOrBuilder();

    /**
     * <code>required .gazebo.msgs.Pose pose = 2;</code>
     * @return Whether the pose field is set.
     */
    boolean hasPose();
    /**
     * <code>required .gazebo.msgs.Pose pose = 2;</code>
     * @return The pose.
     */
    gazebo.msgs.PoseOuterClass.Pose getPose();
    /**
     * <code>required .gazebo.msgs.Pose pose = 2;</code>
     */
    gazebo.msgs.PoseOuterClass.PoseOrBuilder getPoseOrBuilder();
  }
  /**
   * Protobuf type {@code gazebo.msgs.PoseStamped}
   */
  public static final class PoseStamped extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gazebo.msgs.PoseStamped)
      PoseStampedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PoseStamped.newBuilder() to construct.
    private PoseStamped(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PoseStamped() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PoseStamped();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gazebo.msgs.PoseStampedOuterClass.internal_static_gazebo_msgs_PoseStamped_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gazebo.msgs.PoseStampedOuterClass.internal_static_gazebo_msgs_PoseStamped_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gazebo.msgs.PoseStampedOuterClass.PoseStamped.class, gazebo.msgs.PoseStampedOuterClass.PoseStamped.Builder.class);
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private gazebo.msgs.TimeOuterClass.Time time_;
    /**
     * <pre>
     * Time when the data was captured
     * </pre>
     *
     * <code>required .gazebo.msgs.Time time = 1;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Time when the data was captured
     * </pre>
     *
     * <code>required .gazebo.msgs.Time time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public gazebo.msgs.TimeOuterClass.Time getTime() {
      return time_ == null ? gazebo.msgs.TimeOuterClass.Time.getDefaultInstance() : time_;
    }
    /**
     * <pre>
     * Time when the data was captured
     * </pre>
     *
     * <code>required .gazebo.msgs.Time time = 1;</code>
     */
    @java.lang.Override
    public gazebo.msgs.TimeOuterClass.TimeOrBuilder getTimeOrBuilder() {
      return time_ == null ? gazebo.msgs.TimeOuterClass.Time.getDefaultInstance() : time_;
    }

    public static final int POSE_FIELD_NUMBER = 2;
    private gazebo.msgs.PoseOuterClass.Pose pose_;
    /**
     * <code>required .gazebo.msgs.Pose pose = 2;</code>
     * @return Whether the pose field is set.
     */
    @java.lang.Override
    public boolean hasPose() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .gazebo.msgs.Pose pose = 2;</code>
     * @return The pose.
     */
    @java.lang.Override
    public gazebo.msgs.PoseOuterClass.Pose getPose() {
      return pose_ == null ? gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance() : pose_;
    }
    /**
     * <code>required .gazebo.msgs.Pose pose = 2;</code>
     */
    @java.lang.Override
    public gazebo.msgs.PoseOuterClass.PoseOrBuilder getPoseOrBuilder() {
      return pose_ == null ? gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance() : pose_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPose()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTime().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPose().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getTime());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getPose());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTime());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPose());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gazebo.msgs.PoseStampedOuterClass.PoseStamped)) {
        return super.equals(obj);
      }
      gazebo.msgs.PoseStampedOuterClass.PoseStamped other = (gazebo.msgs.PoseStampedOuterClass.PoseStamped) obj;

      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (hasPose() != other.hasPose()) return false;
      if (hasPose()) {
        if (!getPose()
            .equals(other.getPose())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      if (hasPose()) {
        hash = (37 * hash) + POSE_FIELD_NUMBER;
        hash = (53 * hash) + getPose().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gazebo.msgs.PoseStampedOuterClass.PoseStamped prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.PoseStamped}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gazebo.msgs.PoseStamped)
        gazebo.msgs.PoseStampedOuterClass.PoseStampedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gazebo.msgs.PoseStampedOuterClass.internal_static_gazebo_msgs_PoseStamped_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gazebo.msgs.PoseStampedOuterClass.internal_static_gazebo_msgs_PoseStamped_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gazebo.msgs.PoseStampedOuterClass.PoseStamped.class, gazebo.msgs.PoseStampedOuterClass.PoseStamped.Builder.class);
      }

      // Construct using gazebo.msgs.PoseStampedOuterClass.PoseStamped.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTimeFieldBuilder();
          getPoseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        pose_ = null;
        if (poseBuilder_ != null) {
          poseBuilder_.dispose();
          poseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gazebo.msgs.PoseStampedOuterClass.internal_static_gazebo_msgs_PoseStamped_descriptor;
      }

      @java.lang.Override
      public gazebo.msgs.PoseStampedOuterClass.PoseStamped getDefaultInstanceForType() {
        return gazebo.msgs.PoseStampedOuterClass.PoseStamped.getDefaultInstance();
      }

      @java.lang.Override
      public gazebo.msgs.PoseStampedOuterClass.PoseStamped build() {
        gazebo.msgs.PoseStampedOuterClass.PoseStamped result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public gazebo.msgs.PoseStampedOuterClass.PoseStamped buildPartial() {
        gazebo.msgs.PoseStampedOuterClass.PoseStamped result = new gazebo.msgs.PoseStampedOuterClass.PoseStamped(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(gazebo.msgs.PoseStampedOuterClass.PoseStamped result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.time_ = timeBuilder_ == null
              ? time_
              : timeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pose_ = poseBuilder_ == null
              ? pose_
              : poseBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gazebo.msgs.PoseStampedOuterClass.PoseStamped) {
          return mergeFrom((gazebo.msgs.PoseStampedOuterClass.PoseStamped)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gazebo.msgs.PoseStampedOuterClass.PoseStamped other) {
        if (other == gazebo.msgs.PoseStampedOuterClass.PoseStamped.getDefaultInstance()) return this;
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        if (other.hasPose()) {
          mergePose(other.getPose());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTime()) {
          return false;
        }
        if (!hasPose()) {
          return false;
        }
        if (!getTime().isInitialized()) {
          return false;
        }
        if (!getPose().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getPoseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private gazebo.msgs.TimeOuterClass.Time time_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.TimeOuterClass.Time, gazebo.msgs.TimeOuterClass.Time.Builder, gazebo.msgs.TimeOuterClass.TimeOrBuilder> timeBuilder_;
      /**
       * <pre>
       * Time when the data was captured
       * </pre>
       *
       * <code>required .gazebo.msgs.Time time = 1;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Time when the data was captured
       * </pre>
       *
       * <code>required .gazebo.msgs.Time time = 1;</code>
       * @return The time.
       */
      public gazebo.msgs.TimeOuterClass.Time getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? gazebo.msgs.TimeOuterClass.Time.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Time when the data was captured
       * </pre>
       *
       * <code>required .gazebo.msgs.Time time = 1;</code>
       */
      public Builder setTime(gazebo.msgs.TimeOuterClass.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
        } else {
          timeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time when the data was captured
       * </pre>
       *
       * <code>required .gazebo.msgs.Time time = 1;</code>
       */
      public Builder setTime(
          gazebo.msgs.TimeOuterClass.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time when the data was captured
       * </pre>
       *
       * <code>required .gazebo.msgs.Time time = 1;</code>
       */
      public Builder mergeTime(gazebo.msgs.TimeOuterClass.Time value) {
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            time_ != null &&
            time_ != gazebo.msgs.TimeOuterClass.Time.getDefaultInstance()) {
            getTimeBuilder().mergeFrom(value);
          } else {
            time_ = value;
          }
        } else {
          timeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time when the data was captured
       * </pre>
       *
       * <code>required .gazebo.msgs.Time time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time when the data was captured
       * </pre>
       *
       * <code>required .gazebo.msgs.Time time = 1;</code>
       */
      public gazebo.msgs.TimeOuterClass.Time.Builder getTimeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Time when the data was captured
       * </pre>
       *
       * <code>required .gazebo.msgs.Time time = 1;</code>
       */
      public gazebo.msgs.TimeOuterClass.TimeOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              gazebo.msgs.TimeOuterClass.Time.getDefaultInstance() : time_;
        }
      }
      /**
       * <pre>
       * Time when the data was captured
       * </pre>
       *
       * <code>required .gazebo.msgs.Time time = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.TimeOuterClass.Time, gazebo.msgs.TimeOuterClass.Time.Builder, gazebo.msgs.TimeOuterClass.TimeOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gazebo.msgs.TimeOuterClass.Time, gazebo.msgs.TimeOuterClass.Time.Builder, gazebo.msgs.TimeOuterClass.TimeOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      private gazebo.msgs.PoseOuterClass.Pose pose_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.PoseOuterClass.Pose, gazebo.msgs.PoseOuterClass.Pose.Builder, gazebo.msgs.PoseOuterClass.PoseOrBuilder> poseBuilder_;
      /**
       * <code>required .gazebo.msgs.Pose pose = 2;</code>
       * @return Whether the pose field is set.
       */
      public boolean hasPose() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .gazebo.msgs.Pose pose = 2;</code>
       * @return The pose.
       */
      public gazebo.msgs.PoseOuterClass.Pose getPose() {
        if (poseBuilder_ == null) {
          return pose_ == null ? gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance() : pose_;
        } else {
          return poseBuilder_.getMessage();
        }
      }
      /**
       * <code>required .gazebo.msgs.Pose pose = 2;</code>
       */
      public Builder setPose(gazebo.msgs.PoseOuterClass.Pose value) {
        if (poseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pose_ = value;
        } else {
          poseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Pose pose = 2;</code>
       */
      public Builder setPose(
          gazebo.msgs.PoseOuterClass.Pose.Builder builderForValue) {
        if (poseBuilder_ == null) {
          pose_ = builderForValue.build();
        } else {
          poseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Pose pose = 2;</code>
       */
      public Builder mergePose(gazebo.msgs.PoseOuterClass.Pose value) {
        if (poseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            pose_ != null &&
            pose_ != gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance()) {
            getPoseBuilder().mergeFrom(value);
          } else {
            pose_ = value;
          }
        } else {
          poseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Pose pose = 2;</code>
       */
      public Builder clearPose() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pose_ = null;
        if (poseBuilder_ != null) {
          poseBuilder_.dispose();
          poseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Pose pose = 2;</code>
       */
      public gazebo.msgs.PoseOuterClass.Pose.Builder getPoseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPoseFieldBuilder().getBuilder();
      }
      /**
       * <code>required .gazebo.msgs.Pose pose = 2;</code>
       */
      public gazebo.msgs.PoseOuterClass.PoseOrBuilder getPoseOrBuilder() {
        if (poseBuilder_ != null) {
          return poseBuilder_.getMessageOrBuilder();
        } else {
          return pose_ == null ?
              gazebo.msgs.PoseOuterClass.Pose.getDefaultInstance() : pose_;
        }
      }
      /**
       * <code>required .gazebo.msgs.Pose pose = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gazebo.msgs.PoseOuterClass.Pose, gazebo.msgs.PoseOuterClass.Pose.Builder, gazebo.msgs.PoseOuterClass.PoseOrBuilder> 
          getPoseFieldBuilder() {
        if (poseBuilder_ == null) {
          poseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gazebo.msgs.PoseOuterClass.Pose, gazebo.msgs.PoseOuterClass.Pose.Builder, gazebo.msgs.PoseOuterClass.PoseOrBuilder>(
                  getPose(),
                  getParentForChildren(),
                  isClean());
          pose_ = null;
        }
        return poseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gazebo.msgs.PoseStamped)
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.PoseStamped)
    private static final gazebo.msgs.PoseStampedOuterClass.PoseStamped DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gazebo.msgs.PoseStampedOuterClass.PoseStamped();
    }

    public static gazebo.msgs.PoseStampedOuterClass.PoseStamped getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PoseStamped>
        PARSER = new com.google.protobuf.AbstractParser<PoseStamped>() {
      @java.lang.Override
      public PoseStamped parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PoseStamped> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PoseStamped> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public gazebo.msgs.PoseStampedOuterClass.PoseStamped getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_PoseStamped_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gazebo_msgs_PoseStamped_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022pose_stamped.proto\022\013gazebo.msgs\032\ntime." +
      "proto\032\npose.proto\"O\n\013PoseStamped\022\037\n\004time" +
      "\030\001 \002(\0132\021.gazebo.msgs.Time\022\037\n\004pose\030\002 \002(\0132" +
      "\021.gazebo.msgs.Pose"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gazebo.msgs.TimeOuterClass.getDescriptor(),
          gazebo.msgs.PoseOuterClass.getDescriptor(),
        });
    internal_static_gazebo_msgs_PoseStamped_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gazebo_msgs_PoseStamped_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gazebo_msgs_PoseStamped_descriptor,
        new java.lang.String[] { "Time", "Pose", });
    gazebo.msgs.TimeOuterClass.getDescriptor();
    gazebo.msgs.PoseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
